'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { PublicLayout } from '@/components/PublicLayout';
import { Shield, Mail, Building2, FileText, CheckCircle } from 'lucide-react';

/**
 * REGULATOR ACCESS REQUEST PAGE
 * 
 * PURPOSE:
 * - Provide clear path for regulators/inspectors to request access
 * - No customer account required
 * - Factual, non-marketing tone
 * 
 * AUDIENCE:
 * - FRA inspectors
 * - OSHA auditors
 * - EPA reviewers
 * - Other authorized regulatory agencies
 */

export default function RegulatorAccessPage() {
  const [formData, setFormData] = useState({
    fullName: '',
    agency: '',
    jurisdiction: '',
    reason: '',
    officialEmail: ''
  });
  const [submitted, setSubmitted] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitting(true);

    try {
      const response = await fetch('/api/contact', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          type: 'regulator_access_request',
          ...formData
        })
      });

      if (response.ok) {
        setSubmitted(true);
      }
    } catch (error) {
      console.error('Submission error:', error);
    } finally {
      setSubmitting(false);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setFormData(prev => ({
      ...prev,
      [e.target.name]: e.target.value
    }));
  };

  if (submitted) {
    return (
      <PublicLayout>
        <div className="min-h-screen bg-slate-950 text-white py-12 px-4">
          <div className="max-w-2xl mx-auto text-center">
            <CheckCircle className="w-16 h-16 text-emerald-400 mx-auto mb-6" />
            <h1 className="text-3xl font-bold mb-4">Request Received</h1>
            <p className="text-lg text-slate-300 mb-8">
              Your regulator access request has been submitted. You will receive a response at the email address provided within 2 business days.
            </p>
            <Link
              href="/"
              className="inline-block px-6 py-3 bg-slate-800 hover:bg-slate-700 rounded-lg transition-colors"
            >
              Return to Home
            </Link>
          </div>
        </div>
      </PublicLayout>
    );
  }

  return (
    <PublicLayout>
      <div className="min-h-screen bg-slate-950 text-white py-12 px-4">
        <div className="max-w-3xl mx-auto">
          {/* Header */}
          <div className="mb-12">
            <div className="flex items-center gap-3 mb-4">
              <Shield className="w-8 h-8 text-blue-400" />
              <h1 className="text-3xl md:text-4xl font-bold text-white">
                Regulator Record Access
              </h1>
            </div>
            <p className="text-lg text-slate-300 leading-relaxed">
              Regulators and authorized inspectors may request read-only access to official compliance records generated by this system.
            </p>
          </div>

          {/* Access Model */}
          <div className="mb-8 p-6 bg-slate-900/50 rounded-lg border border-slate-700">
            <h2 className="text-xl font-semibold text-white mb-4">Access Model</h2>
            <ul className="space-y-3 text-slate-300">
              <li className="flex items-start gap-3">
                <span className="text-blue-400 font-bold mt-1">•</span>
                <span>No customer account required</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="text-blue-400 font-bold mt-1">•</span>
                <span>Read-only access only</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="text-blue-400 font-bold mt-1">•</span>
                <span>Access limited to inspection scope</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="text-blue-400 font-bold mt-1">•</span>
                <span>All access is logged</span>
              </li>
            </ul>
          </div>

          {/* Request Form */}
          <div className="bg-slate-900/50 rounded-lg border border-slate-700 p-6 md:p-8">
            <h2 className="text-2xl font-bold text-white mb-6">Request Inspection Access</h2>
            
            <form onSubmit={handleSubmit} className="space-y-6">
              <div>
                <label htmlFor="fullName" className="block text-sm font-medium text-slate-300 mb-2">
                  Full Name *
                </label>
                <input
                  type="text"
                  id="fullName"
                  name="fullName"
                  required
                  value={formData.fullName}
                  onChange={handleChange}
                  className="w-full px-4 py-3 bg-slate-800 border border-slate-600 rounded-lg text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="John Smith"
                />
              </div>

              <div>
                <label htmlFor="agency" className="block text-sm font-medium text-slate-300 mb-2">
                  Agency / Authority *
                </label>
                <input
                  type="text"
                  id="agency"
                  name="agency"
                  required
                  value={formData.agency}
                  onChange={handleChange}
                  className="w-full px-4 py-3 bg-slate-800 border border-slate-600 rounded-lg text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="Federal Railroad Administration"
                />
              </div>

              <div>
                <label htmlFor="jurisdiction" className="block text-sm font-medium text-slate-300 mb-2">
                  Jurisdiction *
                </label>
                <input
                  type="text"
                  id="jurisdiction"
                  name="jurisdiction"
                  required
                  value={formData.jurisdiction}
                  onChange={handleChange}
                  className="w-full px-4 py-3 bg-slate-800 border border-slate-600 rounded-lg text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="Region 5 / State of Illinois"
                />
              </div>

              <div>
                <label htmlFor="reason" className="block text-sm font-medium text-slate-300 mb-2">
                  Reason for Access *
                </label>
                <textarea
                  id="reason"
                  name="reason"
                  required
                  value={formData.reason}
                  onChange={handleChange}
                  rows={4}
                  className="w-full px-4 py-3 bg-slate-800 border border-slate-600 rounded-lg text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="Routine safety inspection of [Organization Name] facilities and employee certification records"
                />
              </div>

              <div>
                <label htmlFor="officialEmail" className="block text-sm font-medium text-slate-300 mb-2">
                  Official Email Address *
                </label>
                <input
                  type="email"
                  id="officialEmail"
                  name="officialEmail"
                  required
                  value={formData.officialEmail}
                  onChange={handleChange}
                  className="w-full px-4 py-3 bg-slate-800 border border-slate-600 rounded-lg text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="inspector@agency.gov"
                />
              </div>

              <div className="pt-4">
                <button
                  type="submit"
                  disabled={submitting}
                  className="w-full px-6 py-4 bg-blue-600 hover:bg-blue-700 disabled:bg-slate-700 disabled:cursor-not-allowed text-white font-semibold rounded-lg transition-colors"
                >
                  {submitting ? 'Submitting...' : 'Submit Access Request'}
                </button>
              </div>
            </form>

            <div className="mt-6 p-4 bg-slate-800/50 rounded border border-slate-600">
              <p className="text-sm text-slate-400">
                <strong>Note:</strong> Access requests are reviewed within 2 business days. You will receive credentials for the official inspection interface at the email address provided.
              </p>
            </div>
          </div>

          {/* Additional Contact */}
          <div className="mt-8 text-center">
            <p className="text-sm text-slate-400 mb-2">Questions about access procedures?</p>
            <a
              href="mailto:support@trexaios.com"
              className="inline-flex items-center gap-2 text-blue-400 hover:text-blue-300 transition-colors"
            >
              <Mail className="w-4 h-4" />
              support@trexaios.com
            </a>
          </div>
        </div>
      </div>
    </PublicLayout>
  );
}
